# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(809, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 60, 321, 421))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.006, x2:1, y2:1, stop:0 rgba(135, 214, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.title_welcom = QtWidgets.QLabel(self.frame)
        self.title_welcom.setGeometry(QtCore.QRect(10, 110, 301, 120))
        self.title_welcom.setStyleSheet("#title_welcom{\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Algerian\";\n"
"}")
        self.title_welcom.setObjectName("title_welcom")
        self.designer = QtWidgets.QLabel(self.frame)
        self.designer.setGeometry(QtCore.QRect(10, 170, 241, 61))
        self.designer.setStyleSheet("#designer{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Algerian\";\n"
"}")
        self.designer.setObjectName("designer")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 80, 321, 381))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(250, 10, 71, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 301, 301))
        self.frame_3.setMinimumSize(QtCore.QSize(301, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(0, 25))
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    image: url(:/icons/icons/确认.png);\n"
"}\n"
"\n"
"")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Sign_account = QtWidgets.QLineEdit(self.page_Login)
        self.Sign_account.setMinimumSize(QtCore.QSize(0, 25))
        self.Sign_account.setObjectName("Sign_account")
        self.verticalLayout_6.addWidget(self.Sign_account)
        self.Sign_password = QtWidgets.QLineEdit(self.page_Login)
        self.Sign_password.setMinimumSize(QtCore.QSize(0, 25))
        self.Sign_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Sign_password.setObjectName("Sign_password")
        self.verticalLayout_6.addWidget(self.Sign_password)
        self.Sign_passwordsure = QtWidgets.QLineEdit(self.page_Login)
        self.Sign_passwordsure.setMinimumSize(QtCore.QSize(0, 25))
        self.Sign_passwordsure.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Sign_passwordsure.setObjectName("Sign_passwordsure")
        self.verticalLayout_6.addWidget(self.Sign_passwordsure)
        self.Sign_button = QtWidgets.QPushButton(self.page_Login)
        self.Sign_button.setMinimumSize(QtCore.QSize(0, 35))
        self.Sign_button.setStyleSheet("")
        self.Sign_button.setText("")
        self.Sign_button.setIconSize(QtCore.QSize(35, 35))
        self.Sign_button.setObjectName("Sign_button")
        self.verticalLayout_6.addWidget(self.Sign_button)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.page_Register = QtWidgets.QWidget()
        self.page_Register.setObjectName("page_Register")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Register)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.login_account = QtWidgets.QLineEdit(self.page_Register)
        self.login_account.setMinimumSize(QtCore.QSize(0, 25))
        self.login_account.setObjectName("login_account")
        self.verticalLayout_5.addWidget(self.login_account)
        self.login_password = QtWidgets.QLineEdit(self.page_Register)
        self.login_password.setMinimumSize(QtCore.QSize(0, 25))
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setObjectName("login_password")
        self.verticalLayout_5.addWidget(self.login_password)
        self.Login_button = QtWidgets.QPushButton(self.page_Register)
        self.Login_button.setMinimumSize(QtCore.QSize(0, 35))
        self.Login_button.setStyleSheet("")
        self.Login_button.setText("")
        self.Login_button.setIconSize(QtCore.QSize(35, 35))
        self.Login_button.setObjectName("Login_button")
        self.verticalLayout_5.addWidget(self.Login_button)
        self.stackedWidget_2.addWidget(self.page_Register)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    font: 75 10pt \"Arial\";\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:0.5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setIconSize(QtCore.QSize(5, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.title_welcom.setText(_translate("LoginWindow", "Welcome to \n"
"Semantic Segmentation \n system"))
        self.designer.setText(_translate("LoginWindow", ""))
        self.Sign_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.Sign_password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.Sign_passwordsure.setPlaceholderText(_translate("LoginWindow", "确认密码："))
        self.login_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.login_password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_3.setText(_translate("LoginWindow", "Login in"))
        self.pushButton_2.setText(_translate("LoginWindow", "Sign in"))
import res_rc
